mm-video: fix arithmetic on a pointer to void
Summary:
Use char* instead of void* for this
pointer arithmetic. Fixes the following:

error: arithmetic on a pointer to void
(vdec_msg->msgdata.output_frame.bufferaddr +

Test Plan: verified

Reviewers: randall.rushing, synergy

Reviewed By: synergy

Differential Revision: http://review.codefirex.com/D624

Change-Id: I68afd3f8b085717be81abd0a8a4529f9cdd2c826
Signed-off-by: DHOMD <DHO@dho.im>